/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ellisjoe.cli;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void exampleExecution() {
    }
}
