/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ellisjoe.cli;

import org.junit.jupiter.api.Test;

class CliTest {
    @Test
    void exampleExecution() {
        Cli.main(new String[]{"-n", "world"});
    }
}
